### ISSUE TITLE
feature request: jc --version

### ISSUE THREAD

**Issue by tst2005** [kellyjonbrazil/jc#109]
There is no `jc --version`
but `jc -a` provide lot of informations, one of them is the version.

I suggest to have a `jc --version` answering in human text, something like

```sh
$ jc --version
jc version 1.14.3
Copyright (C) 2019-2021 by Kelly Brazil
Website: https://github.com/kellyjonbrazil/jc
```

I did it with jq
```
$ jc -a | jq -r ' "\(.name) version \(.version)","Copyright (C) 2019-2021 by \(.author)","Website: https://github.com/kellyjonbrazil/jc" '
jc version 1.14.3
Copyright (C) 2019-2021 by Kelly Brazil
Website: https://github.com/kellyjonbrazil/jc
```

With this try I see there is missing informations about Copyright and website.

It should be good to add them in `jc -a`.

Regards,

**Comment by kellyjonbrazil** [comment]
It's funny you mention it because I was just about to add a `-v` version option in the `dev` branch today. I hadn't thought about the copyright info, though - that's a good idea and I'll add it to both the `-a` and new `-v` output. I also added a `-h` so now you don't get the whole helptext every time there is an error, but you can see all of the parsers on-demand.

**Comment by tst2005** [comment]
nice :D
