### ISSUE TITLE
Feature request: add --whois flag

### ISSUE THREAD

**Issue by pry0cc** [kellyjonbrazil/jc#134]
I would love to parse output from the `whois` command!

**Comment by kellyjonbrazil** [comment]
Hi there!

That actually looks like a great command to parse - not sure why I didn't think of it earlier. :)

I'll do some research - on first glance it looks pretty straightforward to parse, but there may be some gotchas I'm not aware of yet.

Thanks for the suggestion!

**Comment by kellyjonbrazil** [comment]
Could you send me a few sample queries you are interested in? I want to make sure I'm covering all of the desired use-cases other than simple `whois google.com` or `whois 1.1.1.1`.

Thanks!

**Comment by kellyjonbrazil** [comment]
Also, in the mean time - have you checked out the RDAP query option for ARIN Whois?

https://www.arin.net/resources/registry/whois/rdap/#rdap-client

I'm not sure if it has everything you are looking for, but could be an interesting option for you:
```
$ curl https://rdap.arin.net/registry/arin_originas0_networksbyoriginas/10745
{
  "rdapConformance" : [ "rdap_level_0", "arin_originas0", "cidr0" ],
  "notices" : [ {
    "title" : "Terms of Service",
    "description" : [ "By using the ARIN RDAP/Whois service, you are agreeing to the RDAP/Whois Terms of Use" ],
    "links" : [ {
      "value" : "https://rdap.arin.net/registry/arin_originas0_networksbyoriginas/10745",
      "rel" : "about",
      "type" : "text/html",
      "href" : "https://www.arin.net/resources/registry/whois/tou/"
    } ]
  }, {
    "title" : "Whois Inaccuracy Reporting",
    "description" : [ "If you see inaccuracies in the results, please visit: " ],
    "links" : [ {
      "value" : "https://rdap.arin.net/registry/arin_originas0_networksbyoriginas/10745",
      "rel" : "about",
      "type" : "text/html",
      "href" : "https://www.arin.net/resources/registry/whois/inaccuracy_reporting/"
    } ]
 ...
}
```

**Comment by kellyjonbrazil** [comment]
After doing some more research I have decided not to tackle this one since there are other command-line tools and python libraries that can do this, as well as other online options outlined above that can be used to get this information in a structured format.

At the end of the day, the `whois` command is just opening a tcp socket and grabbing text from one or more servers, so in essence `jc` would not be converting the `whois` command's output per se, but would be attempting to convert the output of many different whois servers.

I looked into wrapping one of several existing whois parser python libraries. To do this I would have to vendor the library and update it when there are top-level domain changes, so this would not be easily maintainable. Also, I found that the quality of the existing libraries were not to my expectations and I'd have to do quite a bit of data massaging to get the output in a consistent schema.

The easiest library I found to potentially wrap was https://github.com/richardpenman/whois as I could just use the `parse.py` file and call `parse.WhoisEntry.load('google.com', whois_raw_text)`, but even then I would need to scan the input text to find the domain name, which varies in different languages, before parsing. Note that this library, and others, have command-lines that could be used for your purposes as well.

Thanks for your understanding.
