### ISSUE TITLE
jc swallows exit codes

### ISSUE THREAD

**Issue by ilyash** [kellyjonbrazil/jc#137]
When running `jc some_program`, even if `some_program` exits with non-zero exit code, jc exits with zero:

```
$ jc ifconfig eth0
eth0: error fetching interface information: Device not found
[]
$ echo $?
0
```

Otherwise clean and straightforward integration with [Next Generation Shell](https://github.com/ngs-lang/ngs) behaves incorrectly (with regard to errors) due to this issue.

```
``jc ...`` # should throw an exception but can't because exit code is  0
```

**Comment by kellyjonbrazil** [comment]
Thanks for reporting this. Coincidentally, while looking through the code, I was wondering if the exit code clobbering was being noticed by anyone. But then I forgot to make a note about it for a fix. I'll take another look at it - I'm hoping it is an easy fix.

**Comment by kellyjonbrazil** [comment]
I have a proof of concept that I'm working on now. Decided to completely change the approach from the original hack of modifying the command string and running it via the shell to now properly using the subprocess library and capturing stderr, stdout, and exit code.

I wonder what the best approach here is? Should JC always just return the exit code of the failed program? Or in cases where both jc and the user's program fail, should I take the program's exit code and then add `1` for jc's error?

Do you have a preference?

**Comment by ilyash** [comment]
Here are some thoughts:

* Adding 1 would be really confusing, making it impossible to distinguish whether it comes from the subprocess or jc.
* You could pick some exit code somewhere around 100, so there will be very small chance of clash between jc and the subprocess
* Or maybe in case of an error, exit with 1 and return JSON with complete information about the error. I can't tell for sure whether it's good idea, it needs more thought and maybe PoC.

**Comment by kellyjonbrazil** [comment]
Yeah, I think that makes sense. I'll give `jc` errors a `100` exit code and add that number to the other program's exit code. I think `255` is the highest allowed exit code, so I'll see if I need to do a check to make sure the exit code doesn't exceed that. (maybe `sys.exit` already does that)

I like your idea about adding error information to a JSON stream in STDERR. I'm toying with the idea of adding a `-e` flag to print errors as JSON to STDERR and add the individual exit codes and messages or something like that.

**Comment by kellyjonbrazil** [comment]
This is now working on the `dev` branch. I added the following section to the Readme and man page:

### Exit Codes
Any fatal errors within `jc` will generate an exit code of `100`, otherwise the exit code will be `0`. When using the "magic" syntax (e.g. `jc ifconfig eth0`), `jc` will store the exit code of the program being parsed and add it to the `jc` exit code. This way it is easier to tell if an error was from the parsed program or `jc`.

Consider the following examples using `ifconfig`:
- `ifconfig` exit code = `0`, `jc` exit code = `0`, combined exit code = `0` (no errors)
- `ifconfig` exit code = `1`, `jc` exit code = `0`, combined exit code = `1` (error in `ifconfig`)
- `ifconfig` exit code = `0`, `jc` exit code = `100`, combined exit code = `100` (error in `jc`)
- `ifconfig` exit code = `1`, `jc` exit code = `100`, combined exit code = `101` (error in both `ifconfig` and `jc`)

**Comment by kellyjonbrazil** [comment]
v1.15.4 is now available via pip and includes this functionality.
