### ISSUE TITLE
Feature Request: raise an error when running commands in streaming/continuous mode (e.g. `ping` without `-c`)

### ISSUE THREAD

**Issue by macgregor** [kellyjonbrazil/jc#161]
Cool project, its been a nice addition to my work flows.

Right now, commands which stream output continuously dont work, e.g. `ping` without `-c` just kind of sits there forever (yes, I am aware the jc ping documentation calls this out, I'm using this example illustrate my point):
```
$ jc ping 1.2.3.4
(no output until exited)
^C
$ ping 1.2.3.4 | jc --ping
(no output until exited)
^C
```

However, many cli tools do offer support for streaming data continuously between commands via a pipe:
```
$ ping 192.168.1.254 | grep 3
(only shows output that has a 3 in it)
64 bytes from 192.168.1.254: icmp_seq=0 ttl=64 time=3.541 ms
64 bytes from 192.168.1.254: icmp_seq=1 ttl=64 time=3.827 ms
64 bytes from 192.168.1.254: icmp_seq=2 ttl=64 time=3.853 ms
64 bytes from 192.168.1.254: icmp_seq=3 ttl=64 time=8.828 ms
64 bytes from 192.168.1.254: icmp_seq=4 ttl=64 time=3.983 ms
^C
```

Since `jc` was created with automation in mind, It's fair to ask why an automation tool would ever need to do this anyway and say `jc` will never support continuous output. It's probably significant effort for what amounts to supporting an edge use case, but I'd be interested to know if you've considered adding support for this longer term (and technically speaking what challenges would come with it).

In the mean time it would be nice if `jc` could detect and raise an error for commands that would run continuously rather than just sitting there. That would prevent some head scratching and indicate the problem/solution without consulting the docs for a specific command while giving a nod to the fact that "yes, we know about this" so people don't open issues/feature requests like this one :).

**Comment by kellyjonbrazil** [comment]
Hi there!

Thank you for your suggestion. This is similar to #157 where the request is to allow streaming for certain commands that can stream unlimited data. This would include the parsers for `ping`, `ls`, etc. 

Instead of building the complete JSON object and outputing at the end, I would need to build discrete objects and emit them individually as JSON Lines - similar to how many Unix tools stream by line today. It's not impossible, but it will take some thought. I'm not sure whether I will be done with something like a `-s` flag or if I will need to write separate streaming parsers (like `jc --pings` or something like that. I'll have to investigate.

**Comment by kellyjonbrazil** [comment]
Regarding the request to raise an exception when a command can have infinite output, i'm not sure how to detect that. `jc` only parses text, so it doesn't have any knowledge of the command arguments used. (it technically can with the "magic" syntax, but that info is not used today to keep consistency.)

I'm not even sure I could set a timeout since reading of STDIN is a blocking I/O action. It would probably be possible to do something with async or threads, but I think that might get too complex. I'd rather find a way to support these commands with a streaming parser as mentioned above.

**Comment by macgregor** [comment]
Thanks, I am not too familiar with the technical details of how `|` between processes work though i suspected implementing it might get hacky pretty quick. I'll keep an eye on the project and try out streams if you ever implement it. You can keep this open or closed at your discretion.

**Comment by kellyjonbrazil** [comment]
Streaming parsers are now supported in `jc` v1.17.0.

Cheers!
