### ISSUE TITLE
Type error - Bytes vs String in blkid parser

### ISSUE THREAD

**Issue by WGandy** [kellyjonbrazil/jc#182]
I've tried to pass the output of blkid to the parser and simply get this error. I've checked that the data being passed in actually is bytes. 

`>>> type(data3)
<class 'bytes'>`

And

`>>> result = jc.parsers.blkid.parse(data3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/jc/parsers/blkid.py", line 214, in parse
    key = line.split('=', maxsplit=1)[0].lower()
TypeError: a bytes-like object is required, not 'str'
>>> `

**Comment by kellyjonbrazil** [comment]
Hi - thanks for reporting this. Could you copy/paste the `blkid` text here so I can check it out? Thanks!

**Comment by WGandy** [comment]
I swapped in some x's for some of the uuids but this is the basic output. 

`>>> data3
b'/dev/mmcblk0p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="XXXX-XXXX" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="xxxxaf5c-01"\n/dev/mmcblk0p2: LABEL="rootfs" UUID="XXXxaafd-bab1-xxxx-921b-xxxxxx61f505" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="xxxxxf5c-02"\n/dev/sda1: LABEL_FATBOOT="80GB_SPIN" LABEL="80GB_SPIN" UUID="XXXX-1710" BLOCK_SIZE="512" TYPE="vfat"\n'`

**Comment by kellyjonbrazil** [comment]
It looks like it's working on my side. I think it's just the fact that `data3` is a bytes object instead of a string. Can you decode `data3` to utf-8 to make it a string?

**Comment by kellyjonbrazil** [comment]
I added some type-checks in the `dev` branch. This will make the error messages more clear since they appear to be stating the opposite problem due to duck-typing in the stdlib functions. I'll probably release this version (v1.17.3) in the next few days.

I'll close this issue out, since the resolution is to only use a `str` object as input - not a `bytes` object.

BTW, if you are generating the output from the `subprocess` module, be sure to use the `text=True` argument. This may be why your data is coming back as a byte stream instead of a string. This way you won't need to decode it when sending into `jc`.

**Comment by kellyjonbrazil** [comment]
Version 1.17.3 has now been released with the enhanced type-checking.
