### ISSUE TITLE
Support kv pairs with leading whitespace

### ISSUE THREAD

**Issue by yittg** [kellyjonbrazil/jc#197]
Now jc can parse kv pairs like following:
```
$ cat <<EOF | jc --kv -p
fooo: bar
foo: bar
EOF
{
  "fooo": "bar",
  "foo": "bar"
}
```
But failed on the following case, can it be supported also?
```
$ cat <<EOF | jc --kv -p
fooo: bar
 foo: bar
EOF
{
  "fooo": "bar\nfoo: bar"
}
```
The following is also ok:
```
cat <<EOF | jc --kv -p
 foo: bar
fooo: bar
EOF
{
  "foo": "bar",
  "fooo": "bar"
}
```

**Comment by kellyjonbrazil** [comment]
Hi - thanks for reporting this issue! Let me check into this - seems like it should be possible.

**Comment by kellyjonbrazil** [comment]
The k/v parser is based on the `configparser` Python standard library. According to the docs, it behaves the way you are reporting so multi-line values can be supported.

https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

> Values can also span multiple lines, as long as they are indented deeper than the first line of the value. Depending on the parser’s mode, blank lines may be treated as parts of multiline values or ignored.

To preserve multi-line value support and allow indented lines I could modify the `configparser` configuration to allow interpret a blank line between k/v as a separator. This means you would be able to do something like this:
```
fooo: bar

 foo: bar
```
If having a blank line is not acceptable, then I'll have to think about this a bit because changing this behavior could break things for other users.

Of course, there is the option of trimming the leading whitespace before sending to `jc` with something like `awk '{$1=$1};1'` or other `sed` variations:
```
cat <<EOF | awk '{$1=$1};1' | jc --kv -p
fooo: bar
 foo: bar
EOF
```

**Comment by yittg** [comment]
Given the leading space has special meaning, I prefer to provide a builtin leading whitespace trimming option for kv parser, like following, what do you think?
```
$ cat <<EOF | jc --kv -p --trim-leading-space
fooo: bar
 foo: bar
EOF
{
  "fooo": "bar",
  "foo": "bar"
}
```

**Comment by kellyjonbrazil** [comment]
There is currently no mechanism for supplying parser-specific options as `jc` arguments, so this would be a major change to `jc`. Command argument parsing is a big part of the cli code, so this would not be a simple feature to add.

The idea for `jc` is to keep it from being overly configurable. To that end, I've resisted adding too many options - especially parser options. A short term solution here would be to override the builtin k/v parser with a custom one in the custom parser plugin directory, or just create a new parser/plugin that has the desired behavior.
