### ISSUE TITLE
zip based deployment for the Windows binary

### ISSUE THREAD

**Issue by berndgoetz** [kellyjonbrazil/jc#228]
A zip package for the Windows binary would be appreciated.

**Comment by kellyjonbrazil** [comment]
Hi there - thanks for the suggestion. I ended up needing to settle on an MSI package for Windows because of some extra libraries that needed to be installed alongside the binary. I had hoped to be able to 'compile' it to a single binary but there was some broken functionality. This is because `jc` is a python program and it's not actually being compiled, but packaged along with a python interpreter and some 3rd party modules via `pyoxidizer`.

That being said, It's been a while since I have upgraded my `pyoxidizer` environment so it may be possible to do this in the future with newer versions of `pyoxidizer`. Another thing I'm waiting on is for `pyoxidizer` to reduce the package size by removing source code from the packaged python distribution.

**Comment by berndgoetz** [comment]
Hi Kelly, thanks for your heads up. I'm repackaging your msi into a zip file with all files included now (one time install, package the target directory into a zip file including all sub directories, uninstalling jc again). Unzipping it and adding the jc base directory onto the PATH works nicely, the example "cksum * | jc --cksum -p" works nicely.

Some more background: I've developed a developer tools setup and configuration script set for my software development teams in our company, Swiss Re. It is comparable to chocolatey, just very adapted to my company's needs. I'm using zips for all tools. MSI files are too "interactive" and often require admin rights. Updating versions is also more cumbersome if there isn't a version update mechanism built-in. Uninstallation is also often not possible wihout admin rights.

So if you could simply add a simple zipped version of each release, that would be appreciated, but I can live without it.

**Comment by kellyjonbrazil** [comment]
Thanks for the feedback. I may be able to start doing this in the next release.

**Comment by kellyjonbrazil** [comment]
I added a zip package for windows in the latest v1.19.0 release. Can you let me know if that works for you? I did change the `lib` folder to `jclib` to help reduce the possibility of a naming clash in a directory.

**Comment by berndgoetz** [comment]
Hi @kellyjonbrazil - awesome. Sorry, took me longer to find back :-) 

I looked at the zip. Very nice already, indeed. May I suggest a small improvement: Please put all files into a base directory that is callled like the zip file. That allows me to unzip it without parameters. Instead

`unzip jc-1.20.4-windows -d jc-1.20.4-windows`

I can then simply run `unzip jc-1.20.4.windows` without the potential clash of the lib directory in the current directory I'm in. That allows you to rename the jclib directory back to lib. 

But just minors. Already very helpful, thanks a ton! A nice tool you've created here.

**Comment by kellyjonbrazil** [comment]
Hi @berndgoetz - no problem! I can do that in the next release in a couple weeks (v1.20.5). Thanks for the suggestions!
