### ISSUE TITLE
Possible locale issue: jc -a and jc -v don't work when LANG=C on Debian Buster

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#231]
I've installed the [latest version of `jc`](https://github.com/kellyjonbrazil/jc/releases/tag/v1.18.6) using the deb on Debian Buster using [this Ansible role](https://galaxy.ansible.com/chriscroome/jc):

```bash
which jc
/usr/local/bin/jc

dpkg -L jc
/.
/usr
/usr/local
/usr/local/bin
/usr/local/bin/jc
/usr/share
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/jc.1
/usr/share/doc
/usr/share/doc/jc
/usr/share/doc/jc/changelog.gz

zgrep jc /usr/share/doc/jc/changelog.gz
jc (1.18.6-1) whatever; urgency=medium
```

And things like `jc ls` work without an issue, but `jc -a` doesn't when `LANG=C`:

```bash
export LANG=C && jc -a
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "jc.cli", line 417, in main
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 366: ordinal not in range(128)
```

Nor does `jc -v`:

```bash
export LANG=C && jc -v 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "jc.cli", line 429, in main
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 55: ordinal not in range(128)
```

With `LANG=en_GB.UTF-8` there isn't a problem:

```bash
export LANG=en_GB.UTF-8 && jc -v
jc version 1.18.6
https://github.com/kellyjonbrazil/jc
© 2019-2022 Kelly Brazil
```

This isn't the behaviour expected based on [the documentation](https://github.com/kellyjonbrazil/jc#locale), could it be something odd with my setup? I have tested this locally and on a remove development server both as a regular user and as `root` and the results are consistent.

**Comment by kellyjonbrazil** [comment]
Interesting - seems like it’s getting stuck on the copyright character. This could also be an issue if there happen to be other Unicode characters in the JSON output and the locale is C. I wonder if I’ll need to detect the locale and change to ascii-safe JSON and -v output if Unicode support is not detected. I’ll take a look and see if there is an easy fix. Thanks for reporting this!

**Comment by chriscroome** [comment]
Ah, right, `(c)` is safe US-ASCII ;-)

**Comment by kellyjonbrazil** [comment]
I put a fix for this into the `cli` module. Since there is no really good way to detect the preferred or current encoding type, I ended up checking for `UnicodeEncodeError` and then doing a simple Unicode->ASCII conversion of the string before trying to print again. For JSON content, I do the same, but set `ensure_ascii` to `True` when trying again. This should take care of it.

**Comment by kellyjonbrazil** [comment]
I'm going to release this now in the v1.18.7 release on PIP-only. If things test ok, then I'll bump the github release as well. Thanks!

**Comment by kellyjonbrazil** [comment]
Still working on this one. Looks like the issue only happens when the JSON is being printed so I need to catch the exception then and not while the JSON is being generated. So `jc -v` is working, but `jc -a` is not working yet. I think this might only be an issue with older versions of python, but I should be able to fix this.

**Comment by kellyjonbrazil** [comment]
cool, making some final touches and will release as v1.18.8 in the next day or so.
