### ISSUE TITLE
epoch and epoch_utc

### ISSUE THREAD

**Issue by ilius** [kellyjonbrazil/jc#283]
So I'm working on `ls` module.
But I realized there is something really wrong about `epoch` and `epoch_utc` in the whole project.

```
The `epoch` calculated timestamp field is naive. (i.e. based on the local
time of the system the parser is run on)

The `epoch_utc` calculated timestamp field is timezone-aware and is only
available if the timezone field is UTC.
```

**There is no such thing as Local Epoch / Unix Timestamp!**
Unix timestamp or epoch time or Posix time is *always* based on UTC.
Please check cite notes of Wikipedia:
https://en.wikipedia.org/wiki/Unix_time#cite_note-1

Another hint is that even Python's `datetime.datetime()` does not give you a method for this "local timestamp". You have to manually subtract UTC offset from timestamp.

So I think the `epoch` should be removed, and `epoch_utc` be renamed to `epoch`.
We can add `utc_offset` as a new key if needed.

**Comment by kellyjonbrazil** [comment]
Hi there - thanks for opening this issue! This is a complicated topic and I'll be the first to admit I may have this wrong, but I'll try to lay out why I think `jc` is doing the correct thing.

> There is no such thing as Local Epoch / Unix Timestamp!

I totally agree with this statement. The `_utc` designation (which may be confusing) is not saying the timestamp is in UTC, it is saying the original datetime string had a UTC timezone designation so we are 'aware' of the original timezone. If there is no `_utc` then it just means that there was no timezone information in the original string and we are not going to try to be precise.

Here is another way to look at it. `jc` is only parsing strings. It does not get to make assumptions about where those strings came from. For example:

```
$ date
Mon Sep 12 08:21:18 2022
```
In the above `date` output, there is no timezone information. We could assume the user ran `date` on the local machine and use the local timezone to create an epoch timestamp, but what if this text came from a remote computer? Then we can not say for certain the exact time this happened. `jc` treats this as a Naive datetime string.

Whenever the timezone info is missing or a non-UTC timezone (PDT, etc.) is found we don't bother being precise about generating the epoch timestamp. We just use the local machine's timezone offset and let the user know - this is a naive timestamp so we can't guarantee this event happened at the exact time it says:

```
$ echo 'Mon Sep 12 08:21:18 2022' | jc --date -p 
{
  "year": 2022,
  "month": "Sep",
  "month_num": 9,
  "day": 12,
  "weekday": "Mon",
  "weekday_num": 1,
  "hour": 8,
  "hour_24": 8,
  "minute": 21,
  "second": 18,
  "period": "AM",
  "timezone": null,
  "utc_offset": null,
  "day_of_year": 255,
  "week_of_year": 37,
  "iso": "2022-09-12T08:21:18",
  "epoch": 1662996078,
  "epoch_utc": null,
  "timezone_aware": false
}
```
The string above doesn't contain any timezone information, so `jc` doesn't try to guess - it just assumes the datetime represents a time in the local machine's timezone (in this case, Pacific time) when creating the `epoch` timestamp. And we don't output anything for `epoch_utc` since we can't guarantee the original datetime was in UTC since there is not enough information in the datetime string.

But with the following output, we can be certain of the exact time the event happened:

```
$ echo 'Mon Sep 12 08:21:18 UTC 2022' | jc --date -p
{
  "year": 2022,
  "month": "Sep",
  "month_num": 9,
  "day": 12,
  "weekday": "Mon",
  "weekday_num": 1,
  "hour": 8,
  "hour_24": 8,
  "minute": 21,
  "second": 18,
  "period": "AM",
  "timezone": "UTC",
  "utc_offset": "+0000",
  "day_of_year": 255,
  "week_of_year": 37,
  "iso": "2022-09-12T08:21:18+00:00",
  "epoch": 1662996078,
  "epoch_utc": 1662970878,
  "timezone_aware": true
}
```
`jc` sees the `UTC` timezone in the datetime string, so now we can generate a timezone-aware/precise timestamp called `epoch_utc`. The original `epoch` field is still there and is based on the Pacific timezone (that field never considers the UTC in the datetime - it's just always Naive)

One could argue that if an `epoch_utc` field is generated, then you could change the `epoch` field to be the same instead of keeping it Naive. I wouldn't be against that - it's a bit more complex to document that instead of always being Naive, the `epoch` field might sometimes be timezone-aware.

I hope that makes sense. Sometimes I forget how it works and I need to look back at the code to remember why I did it this way. I'm open to suggestions on how to make it better or clear, though.

Thanks!

**Comment by ilius** [comment]
> In the above date output, there is no timezone information. We could assume the user ran date on the local machine and use the local timezone to create an epoch timestamp, but what if this text came from a remote computer? Then we can not say for certain the exact time this happened. jc treats this as a Naive datetime string.

We should read the `TZ` environment variable (before we read `/etc/timezone` or other system-specific files) which can be set while running `jc` in the very edge case that text comes from a remote machine. In other words, we should always assume the environment is correct (including `TZ`), just like every other Unix program. If environment does not match user's expectation, that's not our problem to fix. It's like saying what if the `/bin/ls` binary was replaced with a made-up binary that gives completely wrong and non-sense information? ()

The environment is not any less important that arguments or stdin. How much precise or certain we can be depends on the information we are given to (arguments, stdin, environment, system config, etc). We are simply processing information and re-organizing them. It should be a deterministic process (unless there are information that are simply lost and we have no choice but to guess).

PS: Right now if `ls` command points to my own script which runs `/usr/bin/ls` with certain flags, then `jc ls` may not work. Also `jc /bin/ls` or `jc /usr/bin/ls` do not work at all

**Comment by kellyjonbrazil** [comment]
I think `jc` is doing the least astonishing thing today. If there is no timezone information, it assumes the local timezone, but basically tells the user (via the `epoch` vs. `epoch_utc`) that you may or may not want to trust the  precision of this timestamp.

If  the data is coming from `ls` run on the local machine, then the `epoch` timestamp should be correct. (there's just no way for `jc` to guarantee it since the timezone information is missing from the source datetime string)

If the data is coming from `ls` on a remote system (which is not as rare as you might think because `jc` is run in Ansible and other automation scenarios where you are dealing with data coming from remote machines), then `jc` still just uses the local timezone when creating the `epoch` timestamp, but again, it's a signal to the user that there is no guarantee it is precise since there was no timezone info in the original data. In these cases it is common for all machines (remote and local) to use UTC, so this allows you to conclude local and remote times match, even if `jc` can't guarantee it because there is no timezone information in the source datetime strings.

I think your idea of pulling the timezone info from the `TZ` env variable is interesting. It could be used as an offset for generating the timestamp so the user can inject timezone information that may not be in the source string. In that case, I guess it could be the `epoch_utc` timestamp since it would no longer be "Naive". (as long as the user selected the correct timezone/offset)

I would have to research how to correctly parse the `TZ` env variable to get the correct offset, though. Perhaps there is already a `datetime` method or 3rd party library because it looks a little involved. (https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html)

**Comment by kellyjonbrazil** [comment]
> PS: Right now if ls command points to my own script which runs /usr/bin/ls with certain flags, then jc ls may not work. Also jc /bin/ls or jc /usr/bin/ls do not work at all

Yes, today the magic syntax requires the command to be in the path and only the command name (no aliases) can be given. If you need to use an alias or want to reference the absolute path of the command, you must use pipes. For example: `/usr/bin/ls /etc | jc --ls`
