### ISSUE TITLE
Create filter for ipconfig

### ISSUE THREAD

**Issue by fredjohnsen** [kellyjonbrazil/jc#335]
ipconfig output is already in a semi-structured scheme, but, nothing I know can parse it easily / natively in the shell. Thanks.

**Comment by kellyjonbrazil** [comment]
Hi there - thanks for the parser suggestion! Yes, I think it would make sense to parse `ipconfig` output. Do you have some sample output you can copy/paste here? I can spin up a VM and see what the output looks like, but I seem to remember it looks similar to `ifconfig` output.

**Comment by kellyjonbrazil** [comment]
Is this ipconfig on windows? I don’t recognize that output.

**Comment by fredjohnsen** [comment]
macOS

**Comment by kellyjonbrazil** [comment]
Ah gotcha - I didn’t even know about that program for macOS. I’ll check it out!

**Comment by kellyjonbrazil** [comment]
After looking at this a bit, I'm not so sure about creating a parser for this command. I had expected someone to request a parser for `ipconfig` on Windows, but had not heard of this command for macOS before. Is there something this command provides that is not available with other commands (e.g. `ifconfig`) or via `/proc` files?

The format does not seem very easy to parse, so this would be a high level of effort for an obscure command that is not recommended for general use. From the man page:
```
ipconfig is a utility that communicates with the IPConfiguration agent to retrieve
     and set IP configuration parameters.  It should only be used in a test and debug
     context.  Using it for any other purpose is strongly discouraged. Public API's in
     the SystemConfiguration framework are currently the only supported way to access
     and control the state of IPConfiguration.
```

**Comment by fredjohnsen** [comment]
Well, the bit you have pulled from the man page is saying that there are native macOS APIs for SETTING network stuff. That has nothing to do with READING the network configuration. ipconfig output has useful information that isn't really combined in the same way using other binaries, but, obviously I can't make you see the value in it if you don't. Thanks.

**Comment by kellyjonbrazil** [comment]
I'm not completely against it, but - as I said - the level of effort (for me) would be high.

This looks like a formal structured serialization format with some type of grammar. It's not really documented, though it looks like it can be reverse engineered. A lexer/parser library like [lark](https://github.com/lark-parser/lark), [marpa](http://savage.net.au/Marpa.html), etc. would probably need to be used to accurately describe the grammar and create the data structure. I've not done this before, so there would definitely be a learning curve.

Perhaps someone else with some experience in this domain might want to tackle this in the short term? It could open up a whole new class of parsers for `jc`.

p.s. it looks like someone has [made an attempt](https://stackoverflow.com/questions/31612329/parsing-scutil-output-with-perl) at this using the perl marpa library, though I'm not sure if there is a good port of marpa for python.

**Comment by tsibley** [comment]
FWIW, pyparsing is a nice library for creating parsing expression (PEG) grammars in Python. Equivalent to Pegex in Perl.

**Comment by tsibley** [comment]
But also, ipconfig being an Apple tool, is this output some text-based representation of a plist? I’d be surprised if it was bespoke.

**Comment by kellyjonbrazil** [comment]
Thanks @tsibley! I’ll check it out.

**Comment by kellyjonbrazil** [comment]
I’ve been looking into the older Nextstep plist format and this output doesn’t seem to match that, unfortunately. `jc` can handle xml and binary plist files today.  I’ll probably add Nextstep plist support in the next `jc` release.

**Comment by kellyjonbrazil** [comment]
Unfortunately, from what I've been reading, the output of `ipconfig`, `scutils`, etc. are not parsable grammars. I'm not sure what the point is of a command printing unparsable semi-structured output. An attempt could be made but there will always be some strange results with big blobs of string values with this type of output. I'm putting this on the back burner unless anyone else has a path forward on this.

**Comment by fredjohnsen** [comment]
it's a little confusing because you're saying it's unparseable but the output is already in dictionary.

i guess i kind of assume the point of your tool is to make the unparsable parseable. 

Apple has proprietary libs & ones that are buried in frameworks that output data. This can't be as unimaginable to handle as something like Windows Registry... 

If you don't want to do it, ok. Thanks for
looking into it.

**Comment by kellyjonbrazil** [comment]
> it's a little confusing because you're saying it's unparseable but the output is already in dictionary.

It is in a dictionary object internally, but the way Apple decided to serialize the output is not machine readable, but is meant for human consumption. It’s basically the worst type of output possible for parsing as text because there are defined dictionaries and arrays and then a bunch of undefined objects as well as free text strings of key values. There’s not an easy way to disambiguate this in a generalized way. A command-specific parser (e.g. ipconfig vs scutils) may be possible, but because they output in a pseudo dictionary structure you need to rely on grammar because some key values can share lines while others span lines and who’s to know if this is dependent on column width or hard-coded?

>i guess i kind of assume the point of your tool is to make the unparsable parseable.

Not really. I’ve done some super complex parsers but the output at least followed some recognizable rules. I’ve pored over the ipconfig and scutils output looking for regularity or grammar but nothing obvious pops out. In my research I’ve found others have found the same. There are no general libraries to parse this type of text output and it doesn’t follow Apple serialization standards like PLIST. 

> Apple has proprietary libs & ones that are buried in frameworks that output data. This can't be as unimaginable to handle as something like Windows Registry... If you don't want to do it, ok. Thanks for looking into it.

Yes, these tools have access to the actual objects in memory and are not relying on this pseudo serialization output. 

> If you don't want to do it, ok.

It’s not a matter of not wanting to. I just don’t know how to do this in a quality way. Anyone can write `jc` parsers, so if anyone else can figure out how to do this I think it would be a valuable addition to `jc`.

Unfortunately, it seems Apple have almost gone out of their way to make this way more difficult than it needs to be. It would have been very convenient if they just serialized this output to PLIST.
