### ISSUE TITLE
for generic: Cutting Input (from begin / from end)

### ISSUE THREAD

**Issue by muescha** [kellyjonbrazil/jc#341]
# Summary

I like to have options to cut lines from start and from end. This can be useful when using generic parsers with some command outputs.

# Syntax

`+1` cut the first lines
`-1` cut the lines from end (i don't know if `-{number}` make problems as option?)

# Workarounds:

`tail -n +2` or `head` 

but unfortunately on macOS there is no `-1` option, so i need there are some constructs like:

`command options | tail -n +1 | tac | tail -n +11 | tac | jc` or many other solutions with `sed` or `awk`

# Implementation

since all lines are loaded into a lines array, it can be cut easy with the python array functions:`lines[skip_begin:-skip_end]` 
example `newlines = lines[2:-11]`

# Examples

```shell
command param | tail -n +2 | jc --plist
```
becomes: 
```shell
command param | jc --plist +2
```

or:

```shell
command param | tail -n +1 | tac | tail -n +11 | tac | jc --plist
```

becomes: 

```shell
command param | jc --plist +1 -11
```

# Benefits

With this cut options some parsers can be defined as "shortcuts" or as "alias". For example (see #331):

for this:
```
tmutil destinationinfo | tail -n +2 | jc --kv
```

it can defined as:
`--tmutil-destinationinfo` => `--kv +2`

or then just use the magic syntax:

```
jc tmutil destinationinfo
```

# Disclaimer

I know it is the style of command line commands to do only one thing and we should not overload the `jc` with too much options, which can be done by pipe commands. So I am fine if you reject this feature request

**Comment by kellyjonbrazil** [comment]
Hi @muescha - thanks for the feature idea! Like you mentioned, I'd prefer to keep from having too many features in `jc`, but if it is simple enough to implement then this could be really useful. If we were to implement this, I think it would be a CLI-only type of feature, otherwise I'd need to implement this logic down into the individual parsers, which would be a big change. I could see some sort of pre-processor function being called if `[+\-0-9]` are found in the command-line arguments.

**Comment by kellyjonbrazil** [comment]
Thinking about this some more. I wonder if this style of slicing syntax would work? I'm trying to find an easy way to parse the command arguments since the `-` character is used for short/long options. Maybe using the `%` character to signal the start of a slice (kinda looks like a slice with the top and bottom sections separated) and then a python-like slice:
```
$ tmutil destinationinfo | jc %5:-10 --kv
```
Which means: start on the 6th line and stop on the 10th line from the end. It doesn't look like the `%` or `:` characters have special meaning in bash or zsh, so there would be no need for quoting/escaping.

**Comment by muescha** [comment]
The % sign look not like a usual command line syntax. 

If you don't like the `-1` syntax then would stick with the usual command line syntax `[-n|--lines] [+|-]NUM` of the commands [`head`](https://man7.org/linux/man-pages/man1/head.1.html) and [`tail`](https://man7.org/linux/man-pages/man1/head.1.html)

**Comment by kellyjonbrazil** [comment]
Yeah it looks like `%` is a special character in the Windows command prompt, so prob not a good idea to use it. I do like the simplicity and flexibility of the python-style slice syntax, still. I could probably implement it without the preceding `%`:
```
$ jc 1: --kv        # skip first line only
$ jc :-10 --kv    # only cut the last 10 lines
$ jc 5:50 --kv   # skip the first 6 lines and go up to line 49
$ jc -50:-1         # process the last 50 lines except the last line
```

**Comment by kellyjonbrazil** [comment]
I have implemented the slicing feature in the `dev` branch. It works as outlined above. Just need to write some tests and update the docs for this to be included in the next release.

**Comment by kellyjonbrazil** [comment]
Here's an example with the `dev` code. `jc` tries to be efficient with the memory utilization by using generators/iterators when possible. Positive number slices are the most memory efficient, while negative slices are less efficient.
```
$ cat kvtest 
line1
line2
line3
line4
a = 1
b = 2
c = 3
line8
line9
line10
$ cat kvtest | jc 4:-3 --kv
{"a":"1","b":"2","c":"3"}
```
Here is an analysis of the memory consumption with standard and streaming parsers with various slicing values on a file with around 40k lines:
<img width="615" alt="Screenshot 2023-01-24 at 3 01 20 PM" src="https://user-images.githubusercontent.com/24423665/214440302-90b41a27-167c-4487-ab66-39c1aa3cb169.png">

**Comment by kellyjonbrazil** [comment]
Added in v1.23.0

**Comment by muescha** [comment]
thx 👍
