### ISSUE TITLE
Feature Request: Parse ~/.ssh/config

### ISSUE THREAD

**Issue by pomdtr** [kellyjonbrazil/jc#354]
It would be helpful to be able to be able to parse this config file in json format.

It looks like this nodejs library has a parser available already: https://www.npmjs.com/package/ssh-config

**Comment by kellyjonbrazil** [comment]
Hi - thank you for the parser suggestion! I'll check into this as I expect to start working on a new batch of parsers in the coming weeks.

**Comment by kellyjonbrazil** [comment]
It looks like I can use the ssh_config parser from the paramiko library:
https://github.com/paramiko/paramiko/blob/main/paramiko/config.py
```
>>> import sshconf
>>> myconfig = sshconf.SSHConfig.from_text('''
... Host foo
...     HostName foo.bar.baz
...     User me
...     IdentityFile /home/me/.ssh/work_rsa
...     IdentitiesOnly yes
...     LocalForward 10002 127.0.0.1:3306 # mysql
...     LocalForward 58999 127.0.0.1:8999 # the_app''')
>>> myconfig.get_hostnames()
{'*', 'foo'}
>>> myconfig.lookup('foo')
{'hostname': 'foo.bar.baz', 'user': 'me', 'identityfile': ['/home/me/.ssh/work_rsa'], 'identitiesonly': 'yes', 'localforward': ['10002 127.0.0.1:3306 # mysql', '58999 127.0.0.1:8999 # the_app']}
```
I can iterate through `myconfig.get_hostnames()` and create a list of dictionaries to output.

**Comment by pomdtr** [comment]
Cool ! I plan to use this integration to create an ssh extension in my own project : https://github.com/pomdtr/sunbeam

**Comment by kellyjonbrazil** [comment]
It turns out I was able to use the existing `sshd-conf` parser with some minor tweaks to support `ssh` config files.

I have a working version in the `dev` branch. You can test by copying the parser file to your plugin directory:
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/ssh_conf.py

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

Let me know what you think!

**Comment by pomdtr** [comment]
I installed it on my device, the output json looks fine to me.

**Comment by kellyjonbrazil** [comment]
Nice! I'll add some tests and this will be ready for the next release.

**Comment by kellyjonbrazil** [comment]
Added in v1.23.0
