### ISSUE TITLE
jc replaces \n in value with \\n

### ISSUE THREAD

**Issue by zenoweed** [kellyjonbrazil/jc#472]
My `file.ini` has the following key(truncated for obvious reasons)
```
# file.ini

PKEY1=-----BEGIN PUBLIC KEY-----\nMIIBIjT8+aVmb0H\nzdZizSE+nDAQAB\n-----END PUBLIC KEY-----
```
If we pass it to jc we get:
```bash
brian@aspire$ cat file.ini | jc --ini -p -r
{
  "PKEY1": "-----BEGIN PUBLIC KEY-----\\nMIIBIjT8+aVmb0H\\nzdZizSE+nDAQAB\\n-----END PUBLIC KEY-----"
}
```
Pretty sure this is a bug. 

For now I'm piping to `sed 's/\\n/n/g'` because I need this to work.

**Comment by kellyjonbrazil** [comment]
Hi there! This seems to be working as designed since the slash character needs to be escaped since your string already has an escaped new line character in it. If you deserialize the JSON result it should provide the literal `\n` characters present in the INI file. 

Another workaround could be to use actual new lines in the INI file instead of `\n` characters. You need to indent subsequent lines in the INI file for them to be combined into a single value so it may take more tweaking than your sed workaround.

**Comment by zenoweed** [comment]
This is an interesting behavior. Also thank you for the advice. I will keep using the sed option as it just works for now. Sorry for the late reply and good day Kelly!
