### ISSUE TITLE
Freezing with 100% CPU when parsing Xrandr output - 1.23.6

### ISSUE THREAD

**Issue by johan-hoglund** [kellyjonbrazil/jc#490]
When I parse the following Xrandr output, my Python program hangs at 100% CPU and the jc.parse() call does not return. Package installed on Debian with pip3 install.

`xrandr = """'Screen 0: minimum 1024 x 600, current 1024 x 600, maximum 1024 x 600
default connected 1024x600+0+0 0mm x 0mm
1024x600       0.00* 
"""

out = jc.parse('xrandr', xrandr)`

**Comment by johan-hoglund** [comment]
From **parsers/xrandr.py**
`292 def _parse_screen(next_lines: List[str]) -> Optional[Screen]:
293     next_line = next_lines.pop()
294     result = re.match(_screen_pattern, next_line)
295     if not result:
296         next_lines.append(next_line)
297         return None`

If the match fails, the next_line is added back to next_lines and we get stuck in an infinite loop.

**Comment by kellyjonbrazil** [comment]
@lyterk could you take a look?

**Comment by lyterk** [comment]
I don't think I'm gonna be able to take a look for a week or two, have a relative in the hospital

Nov 27, 2023 10:32:58 Kelly Brazil ***@***.***>:

**Comment by kellyjonbrazil** [comment]
@lyterk no problem - sending positive thoughts your way! I'll see if I can take a look in the meantime. Take care!

**Comment by kellyjonbrazil** [comment]
Or maybe a more memory-friendly approach would be to modify the original line list to be a bit more complex.

a `List[Tuple[str, List[str]]]`:
```
[
  (
    line_data_string,
    [
      failed_parser_names
    ]
  ),
]
```
Then there could be a function that takes the line-parser name and returns whether it has failed parsing before.

**Comment by kellyjonbrazil** [comment]
More thoughts on this before I get back to my office this weekend and can actually work on some code.

I see two issues here:

1. The line is not parsing correctly. If we fix the parsing of that line it will fix the issue in the short term
2. There is a larger problem with the logic that allows these infinite loop conditions if parsing is not perfect

Item 1 should be pretty easy to fix and I'll work on that.

Item 2 can be an easy to more complex fix. I outlined two approaches above that are sort of on the extremes of memory efficiency vs. simplicity. Normally we don't run into these issues with `jc` parsers because nearly every other parser uses a simple `for` loop to run through the lines and parse. In this case there is a `while` loop and the size of the iterated list changes as items are popped, parsed, and sometimes re-added to the list if parsing fails.

I think we can solve the infinite loop issues without completely refactoring. Though I am sensitive to memory usage considerations, I don't think this parser works on large enough of datasets for there to be a noticeable issue with using more memory vs. fixing the loops. So I think there may be a happy medium to fixing this that sits between the simplicity of a separate list per line parser and a new data structure for the lines that encodes the parser hits on the other hand.

We could use a dictionary to track the parser hits. This would basically double the memory usage (possibly less if there are duplicate lines in the data):

```
{
  line_data_string: [
    failed_parer_names
  ]
}
```
Then you can test if you should even try parsing the line again via `if 'parser_name' in parser_failed_dict[line_data_string]` or similar.

**Comment by kellyjonbrazil** [comment]
We may also need to update the schema per the last comment here: https://github.com/kellyjonbrazil/jc/pull/455

**Comment by kellyjonbrazil** [comment]
I have a possible fix for the infinite loop issue in `dev`. I added the dictionary to track parser state as outlined above. I didn't mess with any regexes. Tests are passing.

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/xrandr.py

Here is what the output of the original offending input looks like:

```
$ echo 'Screen 0: minimum 1024 x 600, current 1024 x 600, maximum 1024 x 600
default connected 1024x600+0+0 0mm x 0mm
   1024x600 0.00*' | jc --xrandr -p
{
  "screens": [
    {
      "devices": [],
      "screen_number": 0,
      "minimum_width": 1024,
      "minimum_height": 600,
      "current_width": 1024,
      "current_height": 600,
      "maximum_width": 1024,
      "maximum_height": 600
    }
  ]
}
```
Does that look right?

**Comment by kellyjonbrazil** [comment]
I updated the `_device_pattern` regex to make `\(normal left inverted right x axis y axis\)` optional and to make the space before `((?P<dimension_width>\d+)mm x (?P<dimension_height>\d+)mm)?)?` optional.

```
_device_pattern = (
    r"(?P<device_name>.+) "
    + r"(?P<is_connected>(connected|disconnected)) ?"
    + r"(?P<is_primary> primary)? ?"
    + r"((?P<resolution_width>\d+)x(?P<resolution_height>\d+)"
    + r"\+(?P<offset_width>\d+)\+(?P<offset_height>\d+))? "
    + r"(?P<rotation>(normal|right|left|inverted)?) ?"
    + r"(?P<reflection>(X axis|Y axis|X and Y axis)?) ?"
    + r"(\(normal left inverted right x axis y axis\))?"
    + r"( ?((?P<dimension_width>\d+)mm x (?P<dimension_height>\d+)mm)?)?"
```
The new output for the test string looks like this:

```
$ echo 'Screen 0: minimum 1024 x 600, current 1024 x 600, maximum 1024 x 600
default connected 1024x600+0+0 0mm x 0mm
   1024x600 0.00*' | jc --xrandr -p
{
  "screens": [
    {
      "devices": [
        {
          "modes": [
            {
              "resolution_width": 1024,
              "resolution_height": 600,
              "is_high_resolution": false,
              "frequencies": [
                {
                  "frequency": 0.0,
                  "is_current": true,
                  "is_preferred": false
                }
              ]
            }
          ],
          "is_connected": true,
          "is_primary": false,
          "device_name": "default",
          "rotation": "normal",
          "reflection": "normal",
          "resolution_width": 1024,
          "resolution_height": 600,
          "offset_width": 0,
          "offset_height": 0,
          "dimension_width": 0,
          "dimension_height": 0
        }
      ],
      "screen_number": 0,
      "minimum_width": 1024,
      "minimum_height": 600,
      "current_width": 1024,
      "current_height": 600,
      "maximum_width": 1024,
      "maximum_height": 600
    }
  ]
}
```
Seems to be better. Tests are still passing.

**Comment by kellyjonbrazil** [comment]
fixed the schema for changes in https://github.com/kellyjonbrazil/jc/pull/455

**Comment by kellyjonbrazil** [comment]
@johan-hoglund @lyterk Could you check if the parser updates in `dev` are working as expected? 

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/xrandr.py

The file above may be placed in a `jc/jcparsers` folder in your local "App data directory":

- Linux/unix: `$HOME/.local/share/jc/jcparsers`
- macOS: `$HOME/Library/Application Support/jc/jcparsers`
- Windows: `$LOCALAPPDATA\jc\jc\jcparsers`

**Comment by kellyjonbrazil** [comment]
Delivered in v1.24.0: https://github.com/kellyjonbrazil/jc/releases/tag/v1.24.0
