### ISSUE TITLE
Is JC supported for ARM64 ?

### ISSUE THREAD

**Issue by surbhall** [kellyjonbrazil/jc#519]
We are using JC utility and require it to be supported for arm64 based system. Please note that we install this via pip-3 using below command in docker file:
`RUN pip-3 install jc`

We require that this utility be installed via pip-3 in docker file similar to how it is done for x86 system.

**Comment by kellyjonbrazil** [comment]
Hi there! I'm not sure if `jc` will work on ARM64, but I believe it should since it works on Raspberry PI and other non-x86 platforms. There are 3 external libraries `jc` uses: pygments, ruamel.yaml, and xmltodict. If any of those are not supported on the ARM64 platform, then you might get reduced functionality. (e.g. no color support, no YAML support, or no XML parser)

**Comment by surbhall** [comment]
Can this be made available as part as part of jc release in below link so that we can use it 
https://github.com/kellyjonbrazil/jc/releases

I had also sent mail to _team+python@tracker.debian.org and sudipm.mukherjee@gmail.com_ 
but there is no reply as now.

**Comment by kellyjonbrazil** [comment]
Sorry, but the binary compilation is somewhat manual and I don't have access to that architecture. You could compile the binary yourself with the instructions under the `pyoxidizer` folder in the j[c-packaging](https://github.com/kellyjonbrazil/jc-packaging) repository.
