### ISSUE TITLE
Feature request - tree

### ISSUE THREAD

**Issue by chrisbergeron** [kellyjonbrazil/jc#78]
I love using jc and I noticed that tree support isn't included.  I see that "tree -J" will output json output and my first thought was that this would be awesome with JC.

If this isn't the right place for this request please let me know.  Thanks for an awesome tool!

**Comment by kellyjonbrazil** [comment]
Hi there,

Thanks for the feedback! Yep, this is the right place for feature requests.

I had `tree` on the list in the beginning, but I decided against adding it for a couple reasons:

1. After taking a look at the output it seemed like it might be one of the more difficult commands to parse correctly
2. I tried not to "reinvent the wheel" when commands already had a JSON output option. Since `tree` has the `-J` option it didn't seem like adding it to `jc` would add much value to the community.

I'm glad you're enjoying using `jc` and appreciate the feedback!
Kelly
